project:
  type: website

website:
  title: "mysite"
  navbar:
    left:
      - href: overview.qmd
        text: Overview
      - href: methodology.qmd
        text: Methodology
      - href: Analysis.qmd
        text: Analysis
      - href: Findings.qmd
        text: Results & Discussion

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



